# Generated by Django 3.1.5 on 2021-02-01 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('area', models.CharField(max_length=150, verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Машинист',
                'verbose_name_plural': 'Машинисты',
            },
        ),
        migrations.CreateModel(
            name='Loko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('element_type', models.CharField(choices=[('section', 'родитель'), ('element', 'элемент')], max_length=50, verbose_name='Тип элемента')),
                ('date_start', models.IntegerField(blank=True, null=True, verbose_name='Дата создания')),
                ('date_update', models.IntegerField(blank=True, null=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Локомотив',
                'verbose_name_plural': 'Локомотивы',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('element_type', models.CharField(choices=[('section', 'родитель'), ('element', 'элемент')], max_length=50, verbose_name='Тип элемента')),
                ('date_start', models.IntegerField(blank=True, null=True, verbose_name='Дата создания')),
                ('date_update', models.IntegerField(blank=True, null=True, verbose_name='Дата обновления')),
                ('role', models.ManyToManyField(to='auth.Group', verbose_name='роли')),
                ('section', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routesheet.region', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Регион-участок-станция',
                'verbose_name_plural': 'Регионы-участки-станции',
            },
        ),
        migrations.CreateModel(
            name='Result_trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_start', models.IntegerField(verbose_name='Время начала')),
                ('date_time_end', models.IntegerField(verbose_name='Время окончания')),
                ('smena', models.IntegerField(verbose_name='смена')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Весс поезда')),
                ('gp', models.IntegerField(blank=True, null=True, verbose_name='Груженные вагоны')),
                ('pv', models.IntegerField(blank=True, null=True, verbose_name='Порожние вагоны')),
                ('dt_start', models.IntegerField(verbose_name='Дт на начало операции')),
                ('dt_end', models.IntegerField(verbose_name='Дт на конец операции')),
                ('work_time', models.IntegerField(verbose_name='Общее время работы')),
                ('fact', models.IntegerField(verbose_name='Фактический расход ДТ')),
                ('norm', models.IntegerField(null=True, verbose_name='Нормированный расход ДТ')),
                ('driver', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='routesheet.driver', verbose_name='Машинист')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routesheet.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Маневровая работа',
                'verbose_name_plural': 'Маневровые работы',
            },
        ),
        migrations.CreateModel(
            name='Result_manevr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_start', models.IntegerField(blank=True, null=True, verbose_name='Время начала')),
                ('date_time_end', models.IntegerField(verbose_name='Время окончания')),
                ('smena', models.IntegerField(verbose_name='смена')),
                ('dt_start', models.IntegerField(verbose_name='Дт на начало операции')),
                ('dt_end', models.IntegerField(verbose_name='Дт на конец операции')),
                ('work_time', models.IntegerField(verbose_name='Общее время работы')),
                ('fact', models.IntegerField(verbose_name='Фактический расход ДТ')),
                ('norm', models.IntegerField(null=True, verbose_name='Нормированный расход ДТ')),
                ('driver', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='routesheet.driver', verbose_name='Машинист')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routesheet.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Маневровая работа',
                'verbose_name_plural': 'Маневровые работы',
            },
        ),
        migrations.CreateModel(
            name='Norms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norma_reserv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Норма резервом')),
                ('norma_fix', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Фиксированная норма')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Дистанция')),
                ('coeff', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Коэффициент удельного расхода')),
                ('norm_manevr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Норма маневров')),
                ('norm_plain', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Норма простоев')),
                ('double_in_tail', models.BooleanField(blank=True, null=True, verbose_name='С толкачем')),
                ('no_double', models.BooleanField(blank=True, null=True, verbose_name='Без толкача')),
                ('double_in_head', models.BooleanField(blank=True, null=True, verbose_name='Толкач')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='routesheet.region', verbose_name='Участок')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station', to='routesheet.region', verbose_name='Станция')),
                ('station_arr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_arr', to='routesheet.region', verbose_name='Станция прибытия')),
                ('station_dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_depp', to='routesheet.region', verbose_name='Станция отправления')),
                ('type_loko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routesheet.loko', verbose_name='Тип локомотива')),
            ],
            options={
                'verbose_name': 'Норма',
                'verbose_name_plural': 'Нормы',
            },
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('number_loko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routesheet.loko', verbose_name='№ локомотива')),
            ],
            options={
                'verbose_name': 'Пробег',
                'verbose_name_plural': 'Пробеги',
            },
        ),
        migrations.AddField(
            model_name='loko',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routesheet.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='loko',
            name='section',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routesheet.loko', verbose_name='Родитель'),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equi_dt', models.IntegerField(blank=True, null=True, verbose_name='Экипировка ДТ')),
                ('equi_oil', models.IntegerField(blank=True, null=True, verbose_name='Экипировка маслом')),
                ('date', models.IntegerField(verbose_name='Дата экипировки')),
                ('number_loko', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routesheet.loko', verbose_name='№ локомотива')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routesheet.region', verbose_name='Регион')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routesheet.region', verbose_name='Регион'),
        ),
    ]
