# Generated by Django 3.1.5 on 2021-02-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0002_auto_20210201_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loko',
            name='region',
        ),
        migrations.AddField(
            model_name='loko',
            name='region',
            field=models.ManyToManyField(blank=True, null=True, to='routesheet.Region', verbose_name='Регион'),
        ),
    ]
