# Generated by Django 3.1.5 on 2021-02-08 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0004_auto_20210204_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='active',
            field=models.BooleanField(default=True, null=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='driver',
            name='tabel',
            field=models.IntegerField(null=True, verbose_name='Табельный номер'),
        ),
        migrations.AddField(
            model_name='loko',
            name='active',
            field=models.BooleanField(default=True, null=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='loko',
            name='section',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='routesheet.loko', verbose_name='Родитель'),
        ),
    ]
