# Generated by Django 3.1.5 on 2021-02-08 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0006_norms_ov'),
    ]

    operations = [
        migrations.AddField(
            model_name='norms',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='routesheet.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area', to='routesheet.region', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='region',
            name='section',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='routesheet.region', verbose_name='Родитель'),
        ),
    ]
