# Generated by Django 3.1.5 on 2021-02-08 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0007_auto_20210208_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norms',
            name='coeff',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Коэффициент удельного расхода'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Дистанция'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='norm_manevr',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Норма маневров'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='norm_plain',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Норма простоев'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='norma_fix',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Фиксированная норма'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='norma_reserv',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Норма резервом'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='ov',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Обработка состава'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='routesheet.region', verbose_name='Регион'),
        ),
    ]
