# Generated by Django 3.1.5 on 2021-02-08 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0008_auto_20210208_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norms',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area', to='routesheet.region', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region', to='routesheet.region', verbose_name='Регион'),
        ),
    ]
