# Generated by Django 3.1.5 on 2021-02-10 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0010_norms_type_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loko',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='routesheet.loko', verbose_name='Родитель'),
        ),
    ]
