# Generated by Django 3.1.5 on 2021-02-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0011_auto_20210210_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loko',
            name='region',
            field=models.ManyToManyField(related_name='loko_region', to='routesheet.Region', verbose_name='Регион'),
        ),
    ]
