# Generated by Django 3.1.5 on 2021-02-28 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0012_auto_20210211_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.TextField(verbose_name='Настройки заголовков')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routesheet.region', verbose_name='Регион')),
            ],
        ),
    ]
