# Generated by Django 3.1.5 on 2021-02-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0013_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='settings',
        ),
        migrations.AddField(
            model_name='settings',
            name='dialog',
            field=models.TextField(null=True, verbose_name='Настройки диалогов'),
        ),
        migrations.AddField(
            model_name='settings',
            name='fix_norm',
            field=models.TextField(null=True, verbose_name='Настройки заголовков фиксированных норм'),
        ),
        migrations.AddField(
            model_name='settings',
            name='manevr',
            field=models.TextField(null=True, verbose_name='Настройки заголовков маневровой работы'),
        ),
        migrations.AddField(
            model_name='settings',
            name='truck',
            field=models.TextField(null=True, verbose_name='Настройки заголовков вывоозной работы'),
        ),
    ]
