# Generated by Django 3.1.5 on 2021-02-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0014_auto_20210228_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='dialog',
            field=models.TextField(blank=True, null=True, verbose_name='Настройки диалогов'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='fix_norm',
            field=models.TextField(blank=True, null=True, verbose_name='Настройки заголовков фиксированных норм'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='manevr',
            field=models.TextField(blank=True, null=True, verbose_name='Настройки заголовков маневровой работы'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='truck',
            field=models.TextField(blank=True, null=True, verbose_name='Настройки заголовков вывоозной работы'),
        ),
    ]
