# Generated by Django 3.1.5 on 2021-03-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0015_auto_20210228_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='truck',
            new_name='settings',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='dialog',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='fix_norm',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='manevr',
        ),
    ]
