# Generated by Django 3.1.5 on 2021-03-11 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0017_auto_20210311_0337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result_trail',
            old_name='date_time_end',
            new_name='dateEnd',
        ),
        migrations.RenameField(
            model_name='result_trail',
            old_name='date_time_start',
            new_name='dateStart',
        ),
        migrations.RenameField(
            model_name='result_trail',
            old_name='station_arr',
            new_name='stationArr',
        ),
        migrations.RenameField(
            model_name='result_trail',
            old_name='station_dep',
            new_name='stationDep',
        ),
    ]
