# Generated by Django 3.1.5 on 2021-03-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0020_result_trail_saving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result_trail',
            name='norm',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True, verbose_name='Нормированный расход ДТ'),
        ),
    ]
