# Generated by Django 3.1.5 on 2021-03-11 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0021_auto_20210311_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result_trail',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultStation', to='routesheet.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='result_trail',
            name='stationArr',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='stationArr', to='routesheet.region', verbose_name='Станция прибытия'),
        ),
        migrations.AlterField(
            model_name='result_trail',
            name='stationDep',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='stationDep', to='routesheet.region', verbose_name='Станция отправления'),
        ),
    ]
