# Generated by Django 3.1.5 on 2021-03-26 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0023_result_trail_lokonumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='section',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Area', to='routesheet.region', verbose_name='Родитель'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(verbose_name='Дата смены')),
                ('smena', models.IntegerField(verbose_name='смена')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Весс поезда')),
                ('gp', models.IntegerField(blank=True, null=True, verbose_name='Груженные вагоны')),
                ('pv', models.IntegerField(blank=True, null=True, verbose_name='Порожние вагоны')),
                ('work_time_trail', models.IntegerField(verbose_name='Общее время работы')),
                ('fact_trail', models.IntegerField(verbose_name='Фактический расход ДТ')),
                ('norm_trail', models.DecimalField(decimal_places=1, max_digits=6, null=True, verbose_name='Нормированный расход ДТ')),
                ('saving_saving', models.DecimalField(decimal_places=1, max_digits=6, null=True, verbose_name='Экономия')),
                ('work_time_manevr', models.IntegerField(verbose_name='Общее время работы')),
                ('fact_manevr', models.IntegerField(verbose_name='Фактический расход ДТ')),
                ('norm_manevr', models.DecimalField(decimal_places=1, max_digits=6, null=True, verbose_name='Нормированный расход ДТ')),
                ('saving_manevr', models.DecimalField(decimal_places=1, max_digits=6, null=True, verbose_name='Экономия')),
                ('fact_result', models.IntegerField(verbose_name='Фактический расход ДТ')),
                ('norm_result', models.DecimalField(decimal_places=1, max_digits=6, null=True, verbose_name='Нормированный расход ДТ')),
                ('saving_result', models.DecimalField(decimal_places=1, max_digits=6, null=True, verbose_name='Экономия')),
                ('smenaStart', models.IntegerField(blank=True, null=True, verbose_name='Начало смены')),
                ('smenaEnd', models.IntegerField(blank=True, null=True, verbose_name='Окончание смены')),
                ('driver', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='routesheet.driver', verbose_name='Машинист')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routesheet.region', verbose_name='Регион')),
                ('typeLoko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routesheet.loko', verbose_name='Тип секции')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
    ]
