# Generated by Django 3.1.5 on 2021-04-01 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0026_auto_20210326_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areaReport', to='routesheet.region', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='report',
            name='fact_manevr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Фактический расход ДТ маневровой работы'),
        ),
        migrations.AlterField(
            model_name='report',
            name='fact_result',
            field=models.IntegerField(blank=True, null=True, verbose_name='Фактический расход ДТ за смену'),
        ),
        migrations.AlterField(
            model_name='report',
            name='fact_trail',
            field=models.IntegerField(blank=True, null=True, verbose_name='Фактический расход ДТ на вывозной работе'),
        ),
        migrations.AlterField(
            model_name='report',
            name='lokoNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lokoNumber', to='routesheet.loko', verbose_name='№ секции'),
        ),
        migrations.AlterField(
            model_name='report',
            name='norm_manevr',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True, verbose_name='Нормированный расход ДТ маневровой работы'),
        ),
        migrations.AlterField(
            model_name='report',
            name='norm_result',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True, verbose_name='Нормированный расход ДТ за смену'),
        ),
        migrations.AlterField(
            model_name='report',
            name='norm_trail',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True, verbose_name='Нормированный расход ДТ на вывозной работе'),
        ),
        migrations.AlterField(
            model_name='report',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routesheet.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='report',
            name='saving_manevr',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True, verbose_name='Экономия на маневровой работе'),
        ),
        migrations.AlterField(
            model_name='report',
            name='saving_result',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True, verbose_name='Экономия ДТ за смену'),
        ),
        migrations.AlterField(
            model_name='report',
            name='saving_trail',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True, verbose_name='Экономия на вывозной работе'),
        ),
        migrations.AlterField(
            model_name='report',
            name='typeLoko',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='typeLoko', to='routesheet.loko', verbose_name='Тип секции'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='work_time_manevr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общее время работы маневровой работы'),
        ),
        migrations.AlterField(
            model_name='report',
            name='work_time_trail',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общее время вывозной работы'),
        ),
    ]
