# Generated by Django 3.1.5 on 2021-04-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0027_auto_20210401_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='fact_manevr',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Фактический расход ДТ маневровой работы'),
        ),
        migrations.AlterField(
            model_name='report',
            name='fact_result',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Фактический расход ДТ за смену'),
        ),
        migrations.AlterField(
            model_name='report',
            name='fact_trail',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Фактический расход ДТ на вывозной работе'),
        ),
        migrations.AlterField(
            model_name='report',
            name='gp',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Груженные вагоны'),
        ),
        migrations.AlterField(
            model_name='report',
            name='norm_manevr',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True, verbose_name='Нормированный расход ДТ маневровой работы'),
        ),
        migrations.AlterField(
            model_name='report',
            name='norm_result',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True, verbose_name='Нормированный расход ДТ за смену'),
        ),
        migrations.AlterField(
            model_name='report',
            name='norm_trail',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True, verbose_name='Нормированный расход ДТ на вывозной работе'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pv',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Порожние вагоны'),
        ),
        migrations.AlterField(
            model_name='report',
            name='saving_manevr',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True, verbose_name='Экономия на маневровой работе'),
        ),
        migrations.AlterField(
            model_name='report',
            name='saving_result',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True, verbose_name='Экономия ДТ за смену'),
        ),
        migrations.AlterField(
            model_name='report',
            name='saving_trail',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True, verbose_name='Экономия на вывозной работе'),
        ),
        migrations.AlterField(
            model_name='report',
            name='smenaEnd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Окончание смены'),
        ),
        migrations.AlterField(
            model_name='report',
            name='smenaStart',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Начало смены'),
        ),
        migrations.AlterField(
            model_name='report',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Весс поезда'),
        ),
        migrations.AlterField(
            model_name='report',
            name='work_time_manevr',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Общее время работы маневровой работы'),
        ),
        migrations.AlterField(
            model_name='report',
            name='work_time_trail',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Общее время вывозной работы'),
        ),
    ]
