# Generated by Django 3.1.5 on 2021-04-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0028_auto_20210405_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result_trail',
            name='gp',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Груженные вагоны'),
        ),
        migrations.AlterField(
            model_name='result_trail',
            name='pv',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Порожние вагоны'),
        ),
        migrations.AlterField(
            model_name='result_trail',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Весс поезда'),
        ),
    ]
