# Generated by Django 3.1.5 on 2021-04-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0032_auto_20210414_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='norms',
            name='thrust',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Вытяжка'),
        ),
    ]
