# Generated by Django 3.1.5 on 2021-04-28 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0036_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='element_type',
            field=models.CharField(choices=[('main_menu', 'Главное меню'), ('left_menu', 'Подменю')], max_length=50, verbose_name='Тип элемента'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routesheet.menu', verbose_name='Меню'),
        ),
    ]
