# Generated by Django 3.1.5 on 2021-05-06 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0039_auto_20210506_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='result_manevr',
            name='area',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='areaManevr', to='routesheet.region', verbose_name='Участок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result_trail',
            name='area',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='areaTrail', to='routesheet.region', verbose_name='Участок'),
            preserve_default=False,
        ),
    ]
