# Generated by Django 3.1.5 on 2021-05-06 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0040_auto_20210506_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result_manevr',
            old_name='date_time_end',
            new_name='dateEnd',
        ),
        migrations.RenameField(
            model_name='result_manevr',
            old_name='date_time_start',
            new_name='dateStart',
        ),
        migrations.AddField(
            model_name='result_manevr',
            name='type_loko',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_loko_manevr', to='routesheet.loko', verbose_name='Тип секции'),
            preserve_default=False,
        ),
    ]
