# Generated by Django 3.1.5 on 2021-05-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0041_auto_20210506_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='work_time_prostoy',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Общее время работы маневровой работы'),
        ),
    ]
