# Generated by Django 3.1.5 on 2021-05-14 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routesheet', '0043_auto_20210513_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_report', to='auth.user', verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result_manevr',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_manevr', to='auth.user', verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result_trail',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_trail', to='auth.user', verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
