# Generated by Django 3.1.5 on 2021-06-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0050_result_trail_numberdouble'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result_trail',
            options={'verbose_name': 'Вывощная работа', 'verbose_name_plural': 'Вывозная работы'},
        ),
        migrations.AddField(
            model_name='result_manevr',
            name='xx',
            field=models.BooleanField(blank=True, null=True, verbose_name='Холодный простой'),
        ),
        migrations.AlterField(
            model_name='report',
            name='work_time_prostoy',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Общее время простоя'),
        ),
    ]
