# Generated by Django 3.1.5 on 2021-06-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0051_auto_20210621_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='norms',
            name='burning',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Прожиг'),
        ),
    ]
