# Generated by Django 3.1.5 on 2021-06-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0053_result_manevr_burning'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='dtEnd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ДТ на окончание смены'),
        ),
        migrations.AddField(
            model_name='report',
            name='dtStart',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ДТ на начало смены'),
        ),
    ]
