# Generated by Django 3.1.5 on 2021-07-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0057_auto_20210701_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result_manevr',
            old_name='date_end',
            new_name='dateEnd',
        ),
        migrations.RenameField(
            model_name='result_manevr',
            old_name='date_start',
            new_name='dateStart',
        ),
        migrations.RenameField(
            model_name='result_trail',
            old_name='date_end',
            new_name='dateEnd',
        ),
        migrations.RenameField(
            model_name='result_trail',
            old_name='date_start',
            new_name='dateStart',
        ),
    ]
