# Generated by Django 3.1.5 on 2021-07-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesheet', '0058_auto_20210701_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='bort',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Борт не работает'),
        ),
        migrations.AddField(
            model_name='result_manevr',
            name='bort',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Борт не работает'),
        ),
        migrations.AddField(
            model_name='result_trail',
            name='bort',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Борт не работает'),
        ),
    ]
